---
language: go
go:
- tip
- 1.11.x
- 1.10.x

env:
# Force use of go.mod for dependencies on Go 1.11
- GO111MODULE=on

go_import_path: github.com/dolmen-go/jsonptr-benchmark

before_install:
- go list
# Download runtime dependencies and test dependencies
- "if [[ `go version` = 'go version go1.1'[1-9][.\\ ]* ]]; then go list -test -mod=readonly ; else go get -t -v ./... ; fi"

script:
- go test -bench . -benchmem
